#------------------------------------------------------------------------------
# Author:  Sebastian Bialobrzecki
# E-mail:  sbb@openmailbox.org
# Date:    28.08.2015 (DD.MM.YYYY)
# License: GNU GPL v3 or later
# Purpose: Intermediate Makefile for handy project building
#------------------------------------------------------------------------------
# Define project directories
ROOT_DIR = ../

# Define project utilities
CD   = cd
MAKE = make

all:
	($(CD) $(ROOT_DIR); $(MAKE))

.PHONY: clean all

clean:
	($(CD) $(ROOT_DIR); $(MAKE) $@)
